# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_books_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
