# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20170628_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
