# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20170626_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='content',
            field=models.TextField(default='my first review'),
            preserve_default=False,
        ),
    ]
