# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_auto_20170628_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinedtrips',
            old_name='secret',
            new_name='trip',
        ),
    ]
