# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_reviews_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
